Feat/Accordion
wix-incubator/rich-content pull request #1416
Opened 2020-08-03 07:41 UTC by maimonav

2020-09-13 11:25 UTC, shaulgo requested changes

2020-09-13 11:33 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +  setFocusedPair = (idx, isTitle) => {
done.

2020-09-13 11:39 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    const pairs = this.getDataManager().getPairs();
done.

2020-09-13 11:39 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    if (selection.isCollapsed() && selection.getAnchorOffset() === 0) {
done.

2020-09-13 11:39 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +        idx--;
done.

2020-09-13 11:40 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +      callback: newContentState => onChange(newContentState),
done.

2020-09-13 14:21 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    this.props.shouldFocus?.() && this.focus();
done.

2020-09-15 17:21 UTC, shaulgo requested changes

2020-09-15 17:21 UTC, shaulgo commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  setInPluginEditingMode={setInPluginEditingMode}
rename to isEditor

2020-09-15 17:21 UTC, shaulgo commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  t={t}
check if needed

2020-09-15 17:21 UTC, shaulgo commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  Draggable={Draggable}
```suggestion
                  Draggable={isPluginFocused && Draggable}
```

2020-09-16 07:15 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  Draggable={Draggable}
done.

2020-09-16 07:17 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  t={t}
not needed, removed it.

2020-09-16 07:17 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  setInPluginEditingMode={setInPluginEditingMode}
done.

2020-09-16 07:37 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +  }
done.

2020-09-16 08:35 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +                  Draggable={Draggable}
Need to talk about it, I think we should keep it this way.
In the Editor, I want to always render the draggable items, since if not, it will unmount and mount elements in every focus/out of focus of accordion.

2020-09-16 13:44 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    const direction = this.getDataManager().getDirection();
done.

2020-09-16 13:44 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +      <div className={this.styles[direction]}>
done.

2020-09-16 14:10 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +          this.props
done.

2020-09-16 14:11 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    this.props.onFocusEnd?.();
done.

2020-09-16 14:11 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    const { onError, locale, direction, editorKey } = this.props;
done.

2020-09-16 14:11 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handleBackspaceCommand.js
> +export default (editorState, props) => {
done.

2020-09-16 14:11 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handleBackspaceCommand.js
> +    }
done.

2020-09-16 14:11 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handleKeyCommand.js
> +        newState = handleBackspaceCommand(editorState, props);
done.

2020-09-16 14:12 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +const convertArrayToObject = array => {
done.

2020-09-16 14:12 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +      ref: setEditorRef,
done.

2020-09-16 14:12 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +      contentState,
done.

2020-09-16 14:12 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/InnerRCE.jsx
> +  };
done.

2020-09-16 14:12 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +  shouldFocus: PropTypes.func,
done.

2020-09-16 14:12 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +      },
done.

2020-09-16 14:13 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    this.dataManager = this.getDataManager();
done.

2020-09-16 14:13 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    this.dataManager.reorderPairs(result.source.index, result.destination.index);
done.

2020-09-16 14:13 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +  setFocusedPair = (idx, isTitle) => {
done.

2020-09-16 14:30 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +    const direction = this.getDataManager().getDirection();
done.

2020-09-16 15:02 UTC, maimonav commented on examples/main/src/styles.global.scss
> +        padding: 0px;
done.

2020-09-16 15:03 UTC, maimonav commented on examples/main/src/styles.global.scss
> +    }
done.

2020-09-16 15:03 UTC, maimonav commented on examples/main/src/styles.global.scss
>        }
done.

2020-09-16 17:17 UTC, shaulgo requested changes

2020-09-16 17:17 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/modal-components/accordion-settings.jsx
> +    } = this.props;
check if z-index is needed in the inner rce. (unrelated to the line)

2020-09-16 17:17 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/modal-components/accordion-settings.jsx
> +    store.set('componentData', updatedComponentData);
remove the state from this component. Work with the domain object

2020-09-17 06:48 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +          <NewPairButton placeholder={this.addNewPairPlaceHolder} onClick={this.onClick} />
done.

2020-09-17 07:50 UTC, maimonav commented on packages/plugin-accordion/web/src/components/AccordionPair.jsx
> +            direction={this.state.direction}
done.

2020-09-17 07:53 UTC, maimonav commented on packages/plugin-accordion/web/src/components/NewPairButton.jsx
> +import { Icons } from '../defaults';
done.

2020-09-17 07:54 UTC, maimonav commented on packages/plugin-accordion/web/src/components/ExpandCollapseButton.jsx
> +      transition: 'transform 0.15s linear',
done.

2020-09-17 08:02 UTC, maimonav commented on packages/plugin-accordion/web/src/components/modal-components/accordion-settings.jsx
> +  stateFromProps(props) {
done.

2020-09-17 10:00 UTC, maimonav commented on packages/plugin-accordion/web/src/components/modal-components/accordion-settings.jsx
> +    store.set('componentData', updatedComponentData);
done.

2020-09-21 10:02 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
> +        handleExpandOnlyOne={this.handleExpandOnlyOne}
done.

2020-09-21 11:03 UTC, maimonav commented on packages/plugin-accordion/web/src/components/modal-components/accordion-settings.jsx
> +    } = this.props;
not needed, removed.

2020-09-21 19:18 UTC, shaulgo requested changes

2020-09-21 19:18 UTC, shaulgo commented on packages/plugin-accordion/web/package.json
> +    "react-beautiful-dnd": "10.1.1"
this is a dependency

2020-09-22 06:47 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
> +    const { expandState, expandOnlyOne } = config;
done.

2020-09-22 06:48 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-component.jsx
> +  onClick = () => {
done.

2020-09-22 06:51 UTC, maimonav commented on packages/plugin-accordion/web/package.json
> +    "react-beautiful-dnd": "10.1.1"
done.

2020-09-22 08:14 UTC, maimonav commented on e2e/cypress/dataHooks.js
> +export const ACCORDION_PLUGIN_MODAL = {
done.

2020-09-22 12:10 UTC, maimonav commented on e2e/tests/plugins.e2e.js
> +    });
done.

2020-09-24 11:29 UTC, shaulgo requested changes

2020-09-24 11:29 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/handleKeyCommand.js
> +        newState = handleBackspaceCommand(editorState, onBackspace);
return onBackspace to here.
Add logic for onBackspaceAtBeginingOfContent(or firstBlock) innerRce

2020-09-24 11:29 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/AccordionPairs.jsx
> +  PairWrapper: 'div',
```suggestion
  PairWrapper: React.Fragment,
```

2020-09-24 11:30 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
> +const getPairsAllCollpased = pairs => pairs.map(() => false);
fill is in place, will not work.

2020-09-24 11:30 UTC, maimonav commented on packages/plugin-social-polls/web/src/components/settings/layout-settings-section/LayoutSettingsSection.jsx
> +import { Separator, InfoIcon, LTRIcon, RTLIcon } from 'wix-rich-content-editor-common';
done.

2020-09-24 11:31 UTC, maimonav commented on packages/plugin-commons/web/src/Components/LabeledToggle.jsx
> +      <div className={this.styles.labeled_toggle_root} style={style || {}}>
done.

2020-09-24 11:32 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
> +
done.

2020-09-24 11:33 UTC, maimonav commented on e2e/cypress/support/commands.js
> +Cypress.Commands.add('clickOnAccordionCompPairIconByIdx', idx => {
done.

2020-09-24 11:35 UTC, maimonav commented on packages/plugin-accordion/web/src/components/AccordionPairs.jsx
> +  PairWrapper: 'div',
done.

2020-09-24 12:09 UTC, maimonav commented on e2e/tests/plugins.e2e.js
> +      cy.get(`[data-hook=${SETTINGS_PANEL.DONE}]`).click();
done.

2020-09-24 12:09 UTC, maimonav commented on e2e/tests/plugins.e2e.js
> +      cy.loadRicosEditorAndViewer('accordion-rich-text', usePlugins(plugins.accordion));
done.

2020-09-24 12:09 UTC, maimonav commented on e2e/tests/plugins.e2e.js
> +      cy.loadRicosEditorAndViewer('accordion-rich-text', usePlugins(plugins.accordion));
done.

2020-09-24 12:45 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handleKeyCommand.js
> +        newState = handleBackspaceCommand(editorState, onBackspace);
done.

2020-09-24 13:51 UTC, shaulgo requested changes

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/modal-components/accordion-modal-mobile-header.js
> +import PropTypes from 'prop-types';
rename file to convention

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/modal-components/accordion-modal-mobile-header.js
> +import PropTypes from 'prop-types';
rename all modals

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/defaults.ts
> +export const generateKey = () => Math.floor(Math.random() * 100000) + 1;
Math.random().toString(36).substr(2, 9)

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/defaults.ts
> +      key: generateKey(),
we don't want to save key in content. Don't work on it now

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/icons/InsertPluginIcon.tsx
> +  <svg
remove all ids

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/toolbar/inline-buttons.tsx
> +import { getModalStyles } from 'wix-rich-content-editor-common';
rename to ts instead of tsx. Also fix template and push the template to master.

2020-09-24 13:51 UTC, shaulgo commented on packages/plugin-accordion/web/src/toolbar/inline-buttons.tsx
> +import { getModalStyles } from 'wix-rich-content-editor-common';
same with insert-buttons

2020-09-24 13:51 UTC, shaulgo commented on packages/editor-common/web/statics/styles/general.scss
> +    pointer-events: none;
only for accordion

2020-09-24 14:04 UTC, maimonav commented on packages/plugin-accordion/web/src/components/domain/accordion.ts
> +    }
done.

2020-09-24 14:04 UTC, maimonav commented on packages/plugin-accordion/web/src/components/domain/accordion.ts
> +  changeExpandOnlyOne = () => {
done.

2020-09-24 14:06 UTC, maimonav commented on packages/plugin-accordion/web/src/toolbar/inline-buttons.tsx
> +import { getModalStyles } from 'wix-rich-content-editor-common';
done.

2020-09-24 14:07 UTC, maimonav commented on packages/plugin-accordion/web/src/defaults.ts
> +      key: generateKey(),
sure.

2020-09-24 14:09 UTC, maimonav commented on packages/plugin-accordion/web/src/defaults.ts
> +export const generateKey = () => Math.floor(Math.random() * 100000) + 1;
done.

2020-09-24 14:15 UTC, maimonav commented on packages/plugin-accordion/web/src/components/modal-components/accordion-modal-mobile-header.js
> +import PropTypes from 'prop-types';
done.

2020-09-24 14:17 UTC, maimonav commented on packages/plugin-accordion/web/src/icons/InsertPluginIcon.tsx
> +  <svg
done.

2020-09-24 14:23 UTC, maimonav commented on packages/editor-common/web/statics/styles/general.scss
> +    pointer-events: none;
done.

2020-09-24 16:47 UTC, merged