feat/error toasts
wix-incubator/rich-content pull request #1418
Opened 2020-08-03 09:51 UTC by talevy17

2020-08-27 12:16 UTC, shaulgo requested changes

2020-08-27 12:16 UTC, shaulgo commented on packages/editor-common/web/src/Components/Toast.jsx
> +    ReactModal.setAppElement('body');
try portal

2020-08-27 14:46 UTC, talevy17 commented on packages/editor-common/web/src/Components/Toast.jsx
> +    ReactModal.setAppElement('body');
works great (:

2020-09-10 15:59 UTC, shaulgo requested changes

2020-09-10 15:59 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +                  {this.renderErrorToast(locale)}
1. try to use position fixed instead of portal.
2. if works, it will also not need the locale.

2020-09-15 16:05 UTC, shaulgo requested changes

2020-09-15 16:05 UTC, shaulgo commented on packages/plugin-image/web/src/image-component.jsx
> +    const imageData = data?.length ? data[0] : data;
Is data sometimes undefined?

2020-09-16 11:54 UTC, talevy17 commented on packages/plugin-image/web/src/image-component.jsx
> +    const imageData = data?.length ? data[0] : data;
I don't think it supposed to, but it does depend on the consumer
in storybook one of the error examples didn't pass data on error and it crashed

2020-09-17 15:03 UTC, shaulgo approved these changes

2020-09-17 15:03 UTC, shaulgo commented on packages/editor-common/web/src/Components/ErrorToast.jsx
> +    const { commonPubsub } = this.props;
window.__internaltRicosOnError__ = this.onError

2020-09-23 15:37 UTC, merged