test html plugin url radio
wix-incubator/rich-content pull request #1479
Opened 2020-08-25 08:40 UTC by ShamaySapir

2020-08-25 10:58 UTC, shaulgo requested changes

2020-08-25 10:58 UTC, shaulgo commented on e2e/cypress/support/commands.js
> +Cypress.Commands.add('addHtmlPlugin', (input, data) => {
this should just be a function. It's only used in this file.

2020-08-25 10:58 UTC, shaulgo commented on e2e/cypress/support/commands.js
>      .clear();
I'm not sure exactly what is happening here. The data-hook for the text input should be the same for both html and url.

2020-08-25 16:08 UTC, ShamaySapir commented on e2e/cypress/dataHooks.js
> +  URL: 'htmlEditPanel_radioUrl',
fixed

2020-08-25 16:13 UTC, ShamaySapir commented on e2e/cypress/support/commands.js
> +Cypress.Commands.add('addHtmlPlugin', (input, data) => {
fixed

2020-08-25 16:13 UTC, ShamaySapir commented on e2e/cypress/support/commands.js
>      .clear();
fixed

2020-08-26 09:46 UTC, shaulgo commented on e2e/cypress/support/commands.js
> +function addHtmlPlugin(data) {
```suggestion
function addHtmlPlugin(data, isUrl) {
	 cy.clickOnStaticButton(HTML_PLUGIN.STATIC_TOOLBAR_BUTTON);
	 if (isUrl) {
	   cy.get(`[data-hook*=${HTML_PLUGIN.RADIO_URL}]`).click();
	 }
	 ...
```

2020-08-26 11:22 UTC, ShamaySapir commented on e2e/cypress/support/commands.js
> +function addHtmlPlugin(data) {
fixed

2020-08-26 11:33 UTC, shaulgo approved these changes

2020-08-26 13:21 UTC, merged