FIX: Justify content in viewer
wix-incubator/rich-content pull request #1487
Opened 2020-08-27 09:52 UTC by ShamaySapir

2020-08-27 16:54 UTC, shaulgo requested changes

2020-08-27 16:54 UTC, shaulgo commented on packages/viewer/web/src/utils/convertContentState.jsx
> +            <span className={shouldJustify && styles.justifiedText}>{_child}</span>
this changes the dom structure. I rather we don't change it, unless we have to.

2020-08-27 16:54 UTC, shaulgo commented on packages/viewer/web/src/utils/convertContentState.jsx
> +};
```suggestion
const hasText = ([_, data]) => data[0]?.trim().length > 0
```

2020-08-27 16:54 UTC, shaulgo commented on packages/viewer/web/statics/rich-content-viewer.scss
>    }
```suggestion
  }
  &.hasText {
    white-space: pre-wrap !important;
    & > * {
      white-space: pre-wrap !important;
    }
  }
```

2020-08-27 16:55 UTC, shaulgo commented on packages/viewer/web/src/utils/convertContentState.jsx
> +};
or what about isEmptyBlock from below?

2020-08-30 06:19 UTC, ShamaySapir commented on packages/viewer/web/src/utils/convertContentState.jsx
> +            <span className={shouldJustify && styles.justifiedText}>{_child}</span>
fixed

2020-08-30 06:45 UTC, ShamaySapir commented on packages/viewer/web/src/utils/convertContentState.jsx
> +};
isEmptyBlock checks if there is no text at all, but it considers white spaces as not empty.

2020-08-30 06:57 UTC, ShamaySapir commented on packages/viewer/web/src/utils/convertContentState.jsx
> +};
fixed with trim()

2020-08-30 06:58 UTC, ShamaySapir commented on packages/viewer/web/statics/rich-content-viewer.scss
>    }
fixed

2020-08-30 10:57 UTC, shaulgo commented on packages/viewer/web/statics/rich-content-viewer.scss
>  .justify {
.justify.hasText {

2020-08-30 10:58 UTC, shaulgo commented on packages/viewer/web/statics/rich-content-viewer.scss
> -    white-space: pre-wrap !important;
not sure we should remove this. We need to see why it was added.

2020-09-02 08:16 UTC, ShamaySapir commented on packages/viewer/web/statics/rich-content-viewer.scss
> -    white-space: pre-wrap !important;
fixed

2020-09-06 13:41 UTC, shaulgo requested changes

2020-09-06 13:41 UTC, shaulgo commented on e2e/cypress/support/commands.js
> +    });
```suggestion
    window.navigator.__defineGetter__('userAgent', () => userAgent);
```

2020-09-06 13:41 UTC, shaulgo commented on packages/viewer/web/statics/rich-content-viewer.scss
> +  &.hasTextSafariFirefox {
```suggestion
  &.hasTextAndSafariOrFirefox {
```

2020-09-06 15:42 UTC, ShamaySapir commented on e2e/cypress/support/commands.js
> +    });
fixed

2020-09-06 15:42 UTC, ShamaySapir commented on packages/viewer/web/statics/rich-content-viewer.scss
> +  &.hasTextSafariFirefox {
fixed

2020-09-07 11:48 UTC, shaulgo requested changes

2020-09-07 11:48 UTC, shaulgo commented on e2e/cypress/support/commands.js
>  };
```suggestion    
      cy.visit(getUrl(app, fixtureName, plugins), {
        onBeforeLoad: contentWindow => {
        if (Cypress.env('firefox'))
          setUserAgent(contentWindow, 'firefox');
        },
      }).then(contentWindow => {
        disableTransitions();
        findEditorElement();
        contentWindow.richContentHideTooltips = true;
      });

};
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/rendering.e2e.js
> +import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSERS } from './settings';
```suggestion
import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSER } from './settings';
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/rendering.e2e.js
> +      });
```suggestion
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/rendering.e2e.js
> +  context('firefoxDesktop', () => {
```suggestion
  context('firefoxDesktop', {env: {firefox: true}}, () => {
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/settings.js
> +export const FIREFOX_BROWSERS = [{ width: 1440, height: 900, name: 'firefox' }];
```suggestion
export const FIREFOX_BROWSER = [{ width: 1440, height: 900, name: 'firefox' }];
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSERS } from './settings';
```suggestion
import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSER } from './settings';
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +      browser: FIREFOX_BROWSERS,
```suggestion
      browser: FIREFOX_BROWSER,
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +    });
```suggestion
```

2020-09-07 11:48 UTC, shaulgo commented on e2e/tests/text.e2e.js
> +describe('textFirefox', () => {
```suggestion
describe('textFirefox', {env: {firefox: true}}, () => {
```

2020-09-07 12:36 UTC, ShamaySapir commented on e2e/tests/settings.js
> +export const FIREFOX_BROWSERS = [{ width: 1440, height: 900, name: 'firefox' }];
fixed

2020-09-07 12:36 UTC, ShamaySapir commented on e2e/tests/text.e2e.js
> +import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSERS } from './settings';
fixed

2020-09-07 12:37 UTC, ShamaySapir commented on e2e/tests/text.e2e.js
> +      browser: FIREFOX_BROWSERS,
fixed

2020-09-07 12:37 UTC, ShamaySapir commented on e2e/tests/rendering.e2e.js
> +import { DEFAULT_DESKTOP_BROWSERS, FIREFOX_BROWSERS } from './settings';
fixed

2020-09-07 12:39 UTC, ShamaySapir commented on e2e/tests/rendering.e2e.js
> +      });
fixed

2020-09-07 12:39 UTC, ShamaySapir commented on e2e/tests/text.e2e.js
> +    });
fixed

2020-09-07 12:40 UTC, ShamaySapir commented on e2e/tests/text.e2e.js
> +describe('textFirefox', () => {
fixed

2020-09-07 12:41 UTC, ShamaySapir commented on e2e/tests/rendering.e2e.js
> +  context('firefoxDesktop', () => {
fixed

2020-09-07 12:42 UTC, ShamaySapir commented on e2e/cypress/support/commands.js
>  };
fixed

2020-09-07 13:33 UTC, shaulgo approved these changes

2020-09-07 13:39 UTC, merged