[preview] js -> ts
wix-incubator/rich-content pull request #1495
Opened 2020-08-30 13:26 UTC by Barackos

2020-09-10 19:29 UTC, lxgreen reviewed
see my remarks, let's discuss it

2020-09-10 19:29 UTC, lxgreen commented on docs/docs/rcp_api/rich-content-preview.md
> +  _if: metadata => metadata.groupedBlocks.plain.length > 0,
hmm the `groupedBlocks`/`blocks` distinction in API makes it too verbose and reveals implementation details. what if we expose `metadata.textFragments` that returns the block groups like 

```
[
	[ { unstyled }, { unstyled }],
	[ { h2 } ],
	[ { li }, { li }, { li } ],
	[ { quote } ]
]
```

i.e. the groupable blocks are grouped, and non-groupable are not. 

at the moment, the user has to know what text elements are under `groupedBlocks`, and which of them are just under `blocks`, right? also, the term `block` belongs to the draft content state rather content metadata.

2020-09-13 07:51 UTC, Barackos commented on docs/docs/rcp_api/rich-content-preview.md
> +  _if: metadata => metadata.groupedBlocks.plain.length > 0,
Eventually found a way to overcome the need to change the API, as discussed

2020-09-14 10:41 UTC, mharsat requested changes
Awesome work converting this to TS! It's especially helpful in a rather complex package like preview 🚀

What about typing `builder-utils`, `galleryEntityData`, etc.? ☹️
Wht was `RichContentPreview.jsx` left behind 😔

2020-09-14 10:41 UTC, mharsat commented on packages/preview/web/src/ContentStateBuilder/ContentStateBuilder.ts
> +  imageCounter: (settings?: Record<string, unknown>) => ContentStateBuilder;
How about this
```tsx
type A<T> = (data: T) => ContentStateBuilder;
...
h1: A<unknown>;
h2: A<unknown>;
...
image: A<PluginData>;
video: A<PluginData>;
...
```

2020-09-14 10:41 UTC, mharsat commented on packages/preview/web/src/Interactions/interaction-utils.ts
> +          [lastBlockEntityKey]: modifiedEntity as RicosEntity,
Are you sure the content created here is valid RicosContent?

2020-09-14 10:41 UTC, mharsat commented on packages/preview/web/src/Interactions/interactionMap.tsx
>      (map, [key, Component]) => ({
```suggestion
    (map, [key, Component]: [string, ComponentType]) => ({
```
Can be used instead of `as ComponentType` above

2020-09-14 10:41 UTC, mharsat commented on packages/preview/web/src/RuleEngine/ContentStateTransformation.ts
> +interface constructor extends PreviewRule {
Please use an uppercase name for interfaces and types

2020-09-14 10:41 UTC, mharsat commented on packages/preview/web/src/RuleEngine/ContentStateTransformation.ts
>      const previewStateBuilder = new ContentStateBuilder(previewState);
Why is the `|| {}` needed if `ContentStateBuilder`'s `initialState` is allowed to be undefined?

2020-09-15 10:13 UTC, Barackos commented on packages/preview/web/src/Components/ReadMore.tsx
> +  t: (key: string) => string;
Cool!

2020-09-15 10:58 UTC, Barackos commented on packages/preview/web/src/Interactions/interaction-utils.ts
> +          [lastBlockEntityKey]: modifiedEntity as RicosEntity,
fixed - caused by an unneeded check, confused type with boolean.

2020-09-15 10:59 UTC, Barackos commented on packages/preview/web/src/Interactions/interactionMap.tsx
>      (map, [key, Component]) => ({
yup, cool idea

2020-09-15 11:01 UTC, Barackos commented on packages/preview/web/src/ContentStateBuilder/ContentStateBuilder.ts
> +  imageCounter: (settings?: Record<string, unknown>) => ContentStateBuilder;
Inspired by your idea, but slightly different - check it out

2020-09-16 09:59 UTC, Barackos commented
> Awesome work converting this to TS! It's especially helpful in a rather complex package like preview 🚀
> 
> What about typing `builder-utils`, `galleryEntityData`, etc.? ☹️
> Wht was `RichContentPreview.jsx` left behind 😔

Thanks for the comments - fixed & typed `builder-utils`, `galleryEntityData` as well.
Regarding `RichContentPreview.jsx` - it's a little bit problematic: inherits `RichContentViewer` props via `propTypes`, and both are not typed yet. Feels like `RCV` should be TS-converted before `RCP`.

2020-09-16 12:37 UTC, Barackos commented on packages/preview/web/src/ContentStateAnalyzer/ContentStateMetadata.ts
> +  entityMap: RicosContent['entityMap'],
good idea

2020-09-16 12:39 UTC, Barackos commented on packages/preview/web/src/ContentStateBuilder/ContentStateBuilder.ts
> +  ul: (textContent: unknown) => ContentStateBuilder;
The name was indeed implying for something that it isn't.
Updating to `textBlocksWithEntities` soon

2020-09-16 12:51 UTC, mharsat approved these changes
Super!

2020-09-16 14:50 UTC, merged