[ricos-theme] ricos bundlesize optimization
wix-incubator/rich-content pull request #1500
Opened 2020-09-01 11:24 UTC by oded-soffrin

Due to the fact JSS (with jss-preset-default) increase our bundle w/ 12KB (gzipped) and it's a blocker for our consumers to adapt, i've moved theme strategy logic to a different package.

usage for those who wish to use it can be found in tests and storybook. 
(TPA needs to be adjusted in a different branch)

This is just a quickfix, we need to think about replacing JSS (or at least jss-preset-default) with a different, slimmer solution.

2020-09-01 12:18 UTC, mharsat requested changes

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-common/web/src/RicosEngine.tsx
> +      html: [html],
`html` is a bit vague. how about `styling || styles || styleTag || styleElement`?

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-theme/web/src/themes/common.ts
> +import { PaletteColors } from 'ricos-common/src/themeTypes';
```suggestion
import { PaletteColors } from 'ricos-common';
```

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-theme/web/src/themes/editor-common.ts
> +import { PaletteColors } from 'ricos-common/src/themeTypes';
```suggestion
import { PaletteColors } from 'ricos-common';
```

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-theme/web/src/themes/editor.ts
> +import { PaletteColors, ThemeUtils } from 'ricos-common/src/themeTypes';
```suggestion
import { PaletteColors, ThemeUtils } from 'ricos-common';
```

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-theme/web/src/themes/viewer.ts
> +import { PaletteColors, ThemeUtils } from 'ricos-common/src/themeTypes';
```suggestion
import { PaletteColors, ThemeUtils } from 'ricos-common';
```

2020-09-01 12:18 UTC, mharsat commented on packages/ricos-theme/web/tsconfig.json
> +    "allowJs": false
default value, can be removed

2020-09-01 12:22 UTC, oded-soffrin commented on packages/ricos-common/web/src/RicosTypes.ts
> +  createThemeStrategy?: () => ThemeStrategyFunction;
agree on added once to RicosProps, but I thought palette & parenClass should be params supplied to themeStratgey.

2020-09-01 12:26 UTC, Barackos approved these changes

2020-09-01 12:26 UTC, Barackos commented on examples/storybook/stories/Components/EditorWrapper.js
> +        createThemeStrategy={createThemeStrategy}
To simplify the API, I have a suggestion:
- no additional `createThemeStrategy` prop
- instead, `theme` prop API will look something like this:
`theme={createThemeStrategy({ palette, ... })`

- change RicosEngine's field inside the constructor to:
`this.themeStrategy = createThemeStrategy`

- modify the `createThemeStrategy` to accept those fields (palette, cssOverride, fonts..)

2020-09-01 12:26 UTC, oded-soffrin commented on packages/ricos-common/web/src/RicosEngine.tsx
> +      html: [html],
By inetention
I want to make it general. it was rawCss that we wrapped in <style> div. 
My goal was to make generic strategy function, that can add html (in this case styletag, but in other cases, who knows) to the rendering function

2020-09-01 12:27 UTC, oded-soffrin commented on packages/ricos-theme/web/tsconfig.json
> +    "allowJs": false
no comparnede. it's defined in all tsconfig. can we remove from all ?

2020-09-01 12:28 UTC, mharsat commented
> Due to the fact JSS (with jss-preset-default) increase our bundle w/ 12KB (gzipped) and it's a blocker for our consumers to adapt, i've moved theme strategy logic to a different package.
> 
> usage for those who wish to use it can be found in tests and storybook.
> (TPA needs to be adjusted in a different branch)
> 
> This is just a quickfix, we need to think about replacing JSS (or at least jss-preset-default) with a different, slimmer solution.

For replacing JSS we can consider having a presets package, that includes some function that creates custom themes. Something like
```jsx
import { bmPalette, createPalette } from 'ricos-theme';

<RicosEditor theme={{ palette: bmPalette }} />

<RicosEditor theme={{ palette: createPalette(args, that, create, palettes) }} />
```

2020-09-01 12:31 UTC, mharsat commented on packages/ricos-theme/web/tsconfig.json
> +    "allowJs": false
Actually yes we can remove all instances of `"allowJs": false` :)

2020-09-01 13:27 UTC, oded-soffrin commented on packages/ricos-theme/web/tsconfig.json
> +    "allowJs": false
are you talking about 'allowJs' only ?

2020-09-01 13:40 UTC, mharsat commented on packages/ricos-theme/web/tsconfig.json
> +    "allowJs": false
yes, doesn't need to be in this PR

2020-09-03 08:24 UTC, oded-soffrin commented
@Barackos @mharsat @lxgreen updated the API to be 
`theme={createThemeStrategy({ palette })}`

createThemeStrategy is a default export - any better name for examples ? 
maybe `createTheme` ?

other than that take a peek and if looks good i'll update the DOCS and storybook and will merge

2020-09-03 08:32 UTC, Barackos commented
> @Barackos @mharsat @lxgreen updated the API to be
> `theme={createThemeStrategy({ palette })}`
> 
> createThemeStrategy is a default export - any better name for examples ?
> maybe `createTheme` ?
> 
> other than that take a peek and if looks good i'll update the DOCS and storybook and will merge

@oded-soffrin very cool! I think `createTheme` is a good name

2020-09-03 08:54 UTC, mharsat commented
> @Barackos @mharsat @lxgreen updated the API to be
> `theme={createThemeStrategy({ palette })}`
> 
> createThemeStrategy is a default export - any better name for examples ?
> maybe `createTheme` ?
> 
> other than that take a peek and if looks good i'll update the DOCS and storybook and will merge

strategies is an intern implementation term, I also suggest `createTheme` as this is exactly what that does in consumer point of view.
also, I suggest named exports for APIs. we might want to export more things later and named exports provide more flexibility

other than that looks great, go ahead and update the docs

2020-09-03 09:08 UTC, lxgreen approved these changes

2020-09-03 09:13 UTC, mharsat approved these changes

2020-09-03 12:49 UTC, merged