ricos-content
wix-incubator/rich-content pull request #1527
Opened 2020-09-07 07:22 UTC by oded-soffrin

This package was create to seperate normalization logic.
OneApp have a few policy that prevent them from using our normalization:

- upon consuming 'ricos-common' they also get 'image-client-api' which is not related to normalization, and breaks in WebView environment (window dependency)
- They can't deep export 'common/dist/lib...' due to OneApp Police

So the thought is to create a library that is platform agnostic, that will contain ricos content manipulation, validation and creation.

Would love to discuss about naming, and how to build so when we move content state validator it won't bloat ricos-common who depend on it

2020-09-07 08:32 UTC, mharsat requested changes
Looks like a good idea to separate some logic out of the common package.

This seems like the right place to also consolidate all draft-js manipulation utils we let consumers use, only blocker for that is that this is a viewer dependency.

As to `image-client-api`, this is a Wix dependency and should eventually be totally removed from this repo, once we decouple the image plugin from Wix.

Anything blocking us from moving the contentStateValidator and all schemas to here too?

2020-09-07 08:32 UTC, mharsat commented on packages/ricos-content/web/package.json
> +    "wix-rich-content-common": "7.18.3"
These create an interdependency and are not used

2020-09-07 08:32 UTC, mharsat commented on packages/common/web/src/types/index.ts
> +export { ComponentData, RicosContentBlock, RicosContent, RicosEntityRange } from 'ricos-content';
This excludes some types that were exported from common, and is not necessary bc of `export * from 'ricos-content'` in main index.ts file

2020-09-07 08:32 UTC, mharsat commented on packages/ricos-content/web/tests/palettesExample.ts
> +export { wixPalettes };
Why is this file in ricos-content? Seems like a duplicate of both ricos-theme & storybook

2020-09-07 08:53 UTC, oded-soffrin commented on packages/common/web/src/types/index.ts
> +export { ComponentData, RicosContentBlock, RicosContent, RicosEntityRange } from 'ricos-content';
these are all the types that are used outside of that package, I guess we can export all of them but they're just not needed

2020-09-13 09:28 UTC, mharsat approved these changes

2020-09-13 12:44 UTC, shaulgo commented
do we know why the bundles grew?

2020-09-13 13:06 UTC, oded-soffrin commented
Nope. I made this change before plugin-common merge, it might be related. it didn't grow before I've merged from master today...

2020-09-13 15:09 UTC, oded-soffrin commented
@shaulgo it was due to lib bundles this new package separately. 
was added to externals, @mharsat is looking this week on our road toward tree shaking to avoid these cases in the future

2020-09-13 15:18 UTC, merged