[example] feat(exampleApp): files upload native\media manager toggle
wix-incubator/rich-content pull request #1541
Opened 2020-09-09 09:30 UTC by talevy17

2020-09-09 10:42 UTC, shaulgo requested changes

2020-09-09 10:42 UTC, shaulgo commented on examples/main/shared/editor/Editor.jsx
> +      console.log('here');
?

2020-09-09 11:22 UTC, talevy17 commented on examples/main/shared/editor/Editor.jsx
> +      console.log('here');
was added for debugging purposes, removed now
My bad (:

2020-09-10 09:57 UTC, shaulgo approved these changes

2020-09-10 10:34 UTC, merged