Feat/accordion v2
wix-incubator/rich-content pull request #1575
Opened 2020-09-29 09:00 UTC by maimonav

2020-09-30 06:57 UTC, shaulgo requested changes

2020-09-30 06:57 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/InnerRCE.jsx
> +      direction !== state.direction ||
the direction is not used on the state?

2020-09-30 07:28 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/InnerRCE.jsx
> +      direction !== state.direction ||
I only use it in derivedStateFromProps, so I can catch a change in inner-rce and rerender it.

2020-09-30 07:34 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
done.

2020-09-30 07:37 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/blockStyleFn.js
>        data: { textAlignment, dynamicStyles = {} },
done.

2020-09-30 08:27 UTC, maimonav commented on packages/plugin-accordion/web/statics/styles/accordion-component.rtlignore.scss
> +    margin-top: 9px;
done.

2020-09-30 10:15 UTC, shaulgo requested changes

2020-09-30 10:15 UTC, shaulgo commented on packages/plugin-accordion/web/statics/styles/accordion-pair.rtlignore.scss
> +  & > div > div{
fix

2020-09-30 10:21 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/InnerRCE.jsx
> +    const { innerRCERenderedIn, config, editorState, additionalProps } = props;
1. move direction to props. 
2. remove direction from state.

2020-09-30 10:39 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/InnerRCE.jsx
> +    const { innerRCERenderedIn, config, editorState, additionalProps } = props;
1. done.
2. it appears that moving direction to props will not do the trick, since we use derivedStateFromProps, we need to check there that the direction has changed, so I kept the direction in state, unless you have a better solution.

2020-09-30 10:40 UTC, maimonav commented on packages/plugin-accordion/web/statics/styles/accordion-pair.rtlignore.scss
> +  & > div > div{
done.

2020-10-01 14:19 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    this.setState({ editorState: this.copyEditorState(editorState) });
lodash.cloneDeep doesn't work?

2020-10-01 14:25 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    this.setState({ editorState: this.copyEditorState(editorState) });
Checking now.

2020-10-01 14:34 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    this.setState({ editorState: this.copyEditorState(editorState) });
Yes, updated it using only cloneDeep, thanks.

2020-10-04 09:17 UTC, shaulgo approved these changes

2020-10-04 10:30 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    if (nextProps.direction && this.props.direction !== nextProps.direction) {
why?

2020-10-04 10:42 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.jsx
> +    if (nextProps.direction && this.props.direction !== nextProps.direction) {
Nevermind, I'm trying to fix a test that is not related to accordion, I thought maybe this is the issue, still checking.

2020-10-04 11:21 UTC, merged