[ricos-editor] feat: pass setEditorToolbars from ricos-editor
wix-incubator/rich-content pull request #1584
Opened 2020-10-01 09:11 UTC by maimonav

2020-10-01 14:15 UTC, shaulgo requested changes

2020-10-01 15:50 UTC, noamtwix commented on packages/ricos-editor/web/src/RicosEditor.tsx
>              ref: ref => (this.editor = ref),
@maimonav @shaulgo 
we are calling setEditorToolbars with a ref, we are not changing the ref
this.setEditorRef is called just once in the beginning (and not every time we switch from inner/outer editor)
so maybe setting the static toolbars for the first time need to be from the componentDidMount (it will be easier to understand)

2020-10-04 08:38 UTC, shaulgo approved these changes

2020-10-04 08:44 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
>              ref: ref => (this.editor = ref),
@noamtwix I believe that componentDidMount runs only the first time the component is mounted in the dom. But we remount the component when local changes. That's why setStaticToolbar was called in updateLocale. 
Instead of calling it there as well, we can call it when the ref is set. (Like it is now.)

2020-10-04 08:59 UTC, merged