feat/Quote2.0 - improved quote behaviour
wix-incubator/rich-content pull request #1602
Opened 2020-10-05 10:36 UTC by maimonav

2020-10-12 06:56 UTC, shaulgo requested changes

2020-10-12 06:56 UTC, shaulgo commented on e2e/tests/fixtures/multiple-accordions-rich-text.json
> +            "key": "1",
where are this keys made? It looks like a counter. I want to make sure there is not problem with it.

2020-10-12 06:56 UTC, shaulgo commented on packages/viewer/web/src/utils/convertContentState.jsx
> +            {<div className={textClassName}>{_child}</div>}
adding textClassName on the childTag doesn't work?

2020-10-12 06:56 UTC, shaulgo commented on CHANGELOG.md
> +  - [#1602](https://github.com/wix-incubator/rich-content/pull/1602) improved quote behaviour
Let's give a better description of what it does.

2020-10-12 06:56 UTC, shaulgo commented on e2e/tests/fixtures/empty-accordion.json
> +            "key": "20195",
We should take another look at this keys. It could be not very fun if we have duplicate keys.

2020-10-12 06:56 UTC, shaulgo commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
let's add 
1. getPair(id)
2. renderInnerRCV(contentState)

2020-10-12 06:59 UTC, maimonav commented on e2e/tests/fixtures/multiple-accordions-rich-text.json
> +            "key": "1",
I wrote this fixture before we used the key generator, new accordions use the generator.

2020-10-12 07:01 UTC, maimonav commented on e2e/tests/fixtures/empty-accordion.json
> +            "key": "20195",
Pretty sure it's random enough, don't mind this fixture, since I wrote them before we used the key generator.

2020-10-12 07:05 UTC, shaulgo commented
just saying I want to take another look with you next time we talk. It
might already be good enough. We need to remember that in its lifetime It
could be used over a million times.

On Mon, Oct 12, 2020 at 10:01 AM maimonav <notifications@github.com> wrote:

> *@maimonav* commented on this pull request.
> ------------------------------
>
> In e2e/tests/fixtures/empty-accordion.json
> <https://github.com/wix-incubator/rich-content/pull/1602#discussion_r503077594>
> :
>
> > @@ -46,7 +46,7 @@
>          },
>          "pairs": [
>            {
> -            "key": 20195,
> +            "key": "20195",
>
> Pretty sure it's random enough, don't mind this fixture, since I wrote
> them before we used the key generator.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix-incubator/rich-content/pull/1602#discussion_r503077594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPEB37ES3YXXHEM4SC3SKKSWPANCNFSM4SEQL37Q>
> .
>

2020-10-12 07:15 UTC, maimonav commented on CHANGELOG.md
> +  - [#1602](https://github.com/wix-incubator/rich-content/pull/1602) improved quote behaviour
done.

2020-10-12 07:15 UTC, maimonav commented on packages/plugin-accordion/web/src/accordion-viewer.jsx
done.

2020-10-12 07:19 UTC, maimonav commented on packages/viewer/web/src/utils/convertContentState.jsx
> +            {<div className={textClassName}>{_child}</div>}
It might, but now it's the same DOM structure as the editor, so I thought this would be better.

2020-10-14 14:26 UTC, shaulgo approved these changes

2020-10-14 15:22 UTC, merged