[accordion] modal css fixes for tpa
wix-incubator/rich-content pull request #1629
Opened 2020-10-12 12:35 UTC by maimonav

2020-10-14 14:16 UTC, shaulgo requested changes

2020-10-14 14:16 UTC, shaulgo commented on packages/plugin-accordion/web/src/components/modal-components/AccordionSettings.jsx
> +            <p className={this.styles.title}>
move to radioGroupVertical

2020-10-14 14:16 UTC, shaulgo commented on packages/plugin-accordion/web/statics/styles/accordion-settings.scss
> +    margin-block-start: 1em;
fix this

2020-10-15 07:17 UTC, maimonav commented on packages/plugin-accordion/web/src/components/modal-components/AccordionSettings.jsx
> +            <p className={this.styles.title}>
done.

2020-10-15 07:31 UTC, maimonav commented on packages/plugin-accordion/web/statics/styles/accordion-settings.scss
> +    margin-block-start: 1em;
I thought about it again, and I will keep it like that, since this margin is only needed here in the direction_selector_option. If I'll need it in more places I'll refactor.

2020-10-15 10:47 UTC, merged