Infra/remove error blocks in ricos
wix-incubator/rich-content pull request #1637
Opened 2020-10-14 08:07 UTC by talevy17

2020-10-15 06:50 UTC, Barackos commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +import errorBlocksRemover from './errorBlocksRemover';
Let's keep `RicosEditor` clean from additional imports. Idea: add a boolean argument to `getContentState`, let's say "shouldRemoveErrors" / something equivalent, and reposition the `errorBlocksRemover` to be right before the return statement.

2020-10-15 06:57 UTC, Barackos approved these changes

2020-10-18 09:58 UTC, Barackos commented on packages/ricos-common/web/src/RicosTypes.ts
```suggestion
interface ContentStateGetterArgs {
  shouldRemoveErrorBlocks?: boolean;
}
```

2020-10-18 14:34 UTC, Barackos approved these changes
We can enforce object fields. Check my suggestions

2020-10-18 14:34 UTC, Barackos commented on packages/ricos-editor/web/src/utils/editorUtils.ts
> +  const getContentState = ({ shouldRemoveErrorBlocks = false } = {}) => {
```suggestion
  const getContentState: ContentStateGetter = ({ shouldRemoveErrorBlocks } = {}) => {
```

2020-10-21 08:53 UTC, shaulgo requested changes

2020-10-21 08:53 UTC, shaulgo commented on examples/storybook/stories/UploadMedia/Utils/ErrorBlocksRemoalApp.js
> +import React, { Component } from 'react';
fix file name removal

2020-10-21 08:53 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/editorUtils.ts
> +  const getContentState: ContentStateGetter = ({ shouldRemoveErrorBlocks = false } = {}) => {
```suggestion
  const getContentState: ContentStateGetter = ({ shouldRemoveErrorBlocks = true } = {}) => {
```

2020-10-21 08:53 UTC, shaulgo commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +  getContent = (postId?: string, forPublish?: boolean, shouldRemoveErrorBlocks = false) => {
@Barackos what are postId and forPublish?

2020-10-21 08:53 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/errorBlocksRemover.js
> +export default contentState => {
let's give the function a name. Easier to read and debug.

2020-10-21 08:53 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/errorBlocksRemover.js
> +      const { newEntityMap, shouldKeepBlock } = modifyEntityMap(entityRanges, entityMap);
```suggestion
      const { newEntityMap, shouldKeepBlock } = modifyEntityMap(entityKey, entityMap);
```

2020-10-21 08:53 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/errorBlocksRemover.js
> +
isErroredBlock = (block, entityMap) => if (atomic && isErroredEntity(entityKey)

2020-10-21 12:27 UTC, Barackos commented on packages/ricos-editor/web/src/RicosEditor.tsx
> +  getContent = (postId?: string, forPublish?: boolean, shouldRemoveErrorBlocks = false) => {
`postId` is a field we store in our BI when a publish occurs.
`forPublish` explicitly tells us that `getContent` is now being used to retrieve the final content for publish. We ask for this boolean so we won't trigger publish BI on `getContent()` calls that are unrelated to publish.

2020-10-21 13:08 UTC, shaulgo commented
do you know how many consumers are using these functions? I think we
could improve the signature of this function. But it would be a breaking
change.

On Wed, Oct 21, 2020 at 3:27 PM Barackos <notifications@github.com> wrote:

> *@Barackos* commented on this pull request.
> ------------------------------
>
> In packages/ricos-editor/web/src/RicosEditor.tsx
> <https://github.com/wix-incubator/rich-content/pull/1637#discussion_r509234826>
> :
>
> > @@ -68,12 +67,12 @@ export class RicosEditor extends Component<RicosEditorProps, State> {
>
>    getToolbars = () => this.editor.getToolbars();
>
> -  getContent = (postId?: string, forPublish?: boolean) => {
> +  getContent = (postId?: string, forPublish?: boolean, shouldRemoveErrorBlocks = false) => {
>
> postId is a field we store in our BI when a publish occurs.
> forPublish explicitly tells us that getContent is now being used to
> retrieve the final content for publish. We ask for this boolean so we won't
> trigger publish BI on getContent() calls that are unrelated to publish.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/wix-incubator/rich-content/pull/1637#discussion_r509234826>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3OPE6Y2DZFJL6Q42VH4DSL3HSTANCNFSM4SQIMLPA>
> .
>

2020-10-25 11:28 UTC, Barackos commented
@shaulgo From a quick search it seems that [Forum](https://github.com/wix-private/app-market/blob/cd50b1a971d56305b2b4038651e320d62fc80633/communities/communities-forum-client/src/app/components/rich-content-editor/rich-content-editor.js#L590) uses it, but I also remember Challenges (though I can't find their usage in the github search).

I'd love to improve the API. let's discuss.

2020-10-28 10:21 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/errorBlocksRemover.ts
> +  );
```suggestion
  const newBlocks: RicosContentBlock[] = contentState.blocks.filter(!isErrorBlock);
    }
  );
```

2020-10-28 10:23 UTC, shaulgo commented on packages/ricos-editor/web/src/utils/errorBlocksRemover.ts
> +    entityMap: modifyEntityMap(entityMap),
```suggestion
    entityMap: removeEntitiesWithError(entityMap),
```

2020-10-28 10:27 UTC, shaulgo approved these changes
add test for the removal

2020-10-28 14:37 UTC, merged