Convert template to ts
wix-incubator/rich-content pull request #1643
Opened 2020-10-15 10:13 UTC by mharsat

2020-10-20 20:00 UTC, oded-soffrin commented on packages/common/web/src/types/RicosTypes.ts
> +import { GetToolbarSettings, AnchorTarget, RelValue } from '.';
naming - ricosType in common package? intended ?

2020-10-20 20:56 UTC, lxgreen requested changes
please revert both `rich-content-viewer.scss.android.js` and `rich-content-viewer.scss.ios.js`. These two files are here for OneApp workaround, they have to remain `js`. They copied as is to the dist/statics, not transpiled.

2020-10-20 20:56 UTC, lxgreen commented on package.json
> +		"@types/react-i18next/@types/i18next": "11.9.0"
what's the reason?

2020-10-20 20:56 UTC, lxgreen commented on packages/template-atomic-plugin/web/package.json
> +  "private": true,
what's the point to set it private? we'll forget to remove this for sure, and we'll have to release once again after realizing the new plugin is not published. wdyt?

2020-10-20 20:56 UTC, lxgreen commented on scripts/generatePlugin.js
> +        result = result.replace(/"private": true,\n {2}/g, '');
a-ha!

2020-10-20 20:56 UTC, lxgreen commented on scripts/generatePlugin.js
> +      const packageJsonObj = JSON.parse(data);
if you parse it anyways, then just `package.private = false`

2020-10-20 20:56 UTC, lxgreen commented on packages/viewer/web/src/components/Anchors.spec.tsx
> +    if (anchor) anchor.innerHTML = `<div data-hook="ad-id">My Ad!</div>`;
```suggestion
    if (anchor) {
    	anchor.innerHTML = `<div data-hook="ad-id">My Ad!</div>`;
    }
```

2020-10-21 07:00 UTC, mharsat commented on scripts/generatePlugin.js
> +      const packageJsonObj = JSON.parse(data);
That is the example's package.json, to which the new plugin is added as a dependency. Also I prefer not having that field at all

2020-10-21 07:07 UTC, mharsat commented on package.json
> +		"@types/react-i18next/@types/i18next": "11.9.0"
`@types/react-i18next` imports latest `@types/i18next`:
```
    "dependencies": {
        "@types/i18next": "*",
        "@types/react": "*"
    },
```
This causes a mismatch with the one we use. We use a very old version, newer i18next/react-i18next versions have type definitions internally

2020-10-21 07:58 UTC, mharsat commented on packages/common/web/src/types/RicosTypes.ts
> +import { GetToolbarSettings, AnchorTarget, RelValue } from '.';
I moved some of its types that were needed in common - that's a good thing.
I agree naming is bad, gave it another reorg now

2020-10-21 08:30 UTC, lxgreen commented on package.json
> +		"@types/react-i18next/@types/i18next": "11.9.0"
👍

2020-10-21 08:32 UTC, lxgreen commented on scripts/generatePlugin.js
> +      const packageJsonObj = JSON.parse(data);
oh, got it

2020-10-21 19:58 UTC, shaulgo approved these changes

2020-10-21 19:58 UTC, shaulgo commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
why was it moved? It's only used in editor flow.

2020-10-21 20:04 UTC, shaulgo commented on packages/template-atomic-plugin/web/package.json
> +  "private": true,
I think it's fine. No need to release completely half baked plugins.

2020-10-21 20:07 UTC, mharsat commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
True, but it's a negligible amount of code, and I needed its type definition availableto other interfaces in the common package

2020-10-21 20:07 UTC, mharsat commented on packages/common/web/src/Utils/simplePubsub.ts
> +  const subscribe = (key: string, callback: (...args: any[]) => any) => {
Thanks

2020-10-21 20:14 UTC, mharsat commented on packages/template-atomic-plugin/web/package.json
> +  "private": true,
I remove that field later in the [generatePlugin](https://github.com/wix-incubator/rich-content/pull/1643#discussion_r508826994) script in this PR.
@shaulgo I agree that it's better practice not to publish plugins in development. Please decide what flow makes more sense and I'll make the change

2020-10-21 20:34 UTC, shaulgo commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
what's using it? maybe it should also move from common?

2020-10-21 20:43 UTC, mharsat commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
`InlineButton`, `InsertButton`, `TextButtonMapper`, `CreatePluginFunction`

We're basically still following the convenient rule of thumb saying all types are imported from `wix-rich-content-common`. I think it will be easier for all devs to follow this when they need to import types. Also this was the only thing that needed to move in the whole PR, if this sums up to a critical mass in the future we will definitely move things around to editor-common

2020-10-21 21:19 UTC, shaulgo commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Would it make sense to have a types package?

2020-10-22 06:44 UTC, mharsat commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
I considered that actually but I don't see any advantage to that since common is already common to all. Also having a package with almost zero runtime code doesn't make sense

2020-10-22 08:23 UTC, shaulgo commented on packages/template-atomic-plugin/web/package.json
> +  "private": true,
I'm fine with it both ways. But I rather have private=true. 
why is it removed?

2020-10-22 08:25 UTC, mharsat commented on packages/template-atomic-plugin/web/package.json
> +  "private": true,
The template wasn't private before this PR, I made it private bc I moved it to the packages folder.
np I will make it stay private from now on

2020-10-22 09:14 UTC, shaulgo commented on packages/common/web/src/Utils/simplePubsub.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
I don't love it. But we can live with it. Tree shaking will solve this sort of problems.

2020-10-25 18:02 UTC, lxgreen approved these changes
sorry for delay

2020-10-26 11:41 UTC, merged