[editor] feat: copy/paste from google docs & ms word with formatting
wix-incubator/rich-content pull request #1706
Opened 2020-10-29 15:25 UTC by maimonav

Copy/Paste functionalities:

- Support inline styling (line spacing, bold, italic, underline) on lists & headers (all other elements were already supported).

- Fix all bold content from google docs.

- Normalize ms word html.

- Support headers.

- Support alignments.

2020-10-29 18:48 UTC, shaulgo requested changes

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +const replaceWithFragment = (editorState, contentState, contentToPaste) => {
check if it works with the original signature

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +  const shouldOverrideBlockType = blockType => blockType === 'unstyled' || blockType === 'atomic';
override always and only when pasted to block is empty

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  const type = headerElementToDraftType[element] ?? element;
```suggestion
  const type = headerElementToDraftType[element] || 'unstyled';
```

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +    'padding-bottom': style?.paddingTop,
```suggestion
    'padding-bottom': style?.paddingBottom,
```

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/normalizeHTML.js
> +export default function normalizeHTML(htmlString) {
unit test

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +export default function htmlToBlock(nodeName, node) {
unit test

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  return !!nodeTextAlign && nodeTextAlign !== 'start' ? nodeTextAlign : 'left';
recheck this. If no textAlign, then no need to add alignment.

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  type === 'h6';
```suggestion
['li', 'p'].includes(type)
```

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  type === 'h6';
whatever you prefer...

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  if (isElementToBlock(nodeName)) {
```suggestion
  if (shouldConvertElementToBlock(nodeName)) {
```

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +      if (node.parentElement.nodeName === 'OL') {
maybe use ?

2020-10-29 18:48 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +      type = getDraftTypeOfElement(nodeName);
```suggestion
      type = getBlockTypeOfElement(nodeName);
```

2020-11-01 10:07 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +const replaceWithFragment = (editorState, contentState, contentToPaste) => {
done.

2020-11-01 10:10 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +  const shouldOverrideBlockType = blockType => blockType === 'unstyled' || blockType === 'atomic';
done.

2020-11-01 10:13 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  const type = headerElementToDraftType[element] ?? element;
done.

2020-11-01 10:13 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +    'padding-bottom': style?.paddingTop,
done.

2020-11-01 10:16 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  type === 'h6';
done.

2020-11-01 10:17 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +      if (node.parentElement.nodeName === 'OL') {
done.

2020-11-01 10:18 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +      type = getDraftTypeOfElement(nodeName);
done.

2020-11-01 10:18 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  if (isElementToBlock(nodeName)) {
done.

2020-11-01 10:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
> +      .replace('%', '_percent')}`;
done.

2020-11-01 10:36 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +  return !!nodeTextAlign && nodeTextAlign !== 'start' ? nodeTextAlign : 'left';
done.

2020-11-01 12:04 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/normalizeHTML.js
> +export default function normalizeHTML(htmlString) {
done.

2020-11-01 12:05 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/utils/htmlToBlock.js
> +export default function htmlToBlock(nodeName, node) {
Covered by normalizeHTML tests & handlePastedText tests.

2020-11-01 15:15 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +    contentToPaste
let's keep the same signature.

2020-11-01 15:28 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/handlePastedText.js
> +    contentToPaste
Sure.

2020-11-01 19:47 UTC, shaulgo approved these changes

2020-11-01 19:47 UTC, shaulgo commented
add changelog

2020-11-02 09:24 UTC, merged