[plugins-commons] fix: disable inner-focus when accordion is selected
wix-incubator/rich-content pull request #1721
Opened 2020-11-03 12:09 UTC by maimonav

Q&A bug fixes: (will be updated when I fix more issues)

- when multiple blocks are selected, and Accordion is one of them, disable inner-focus of plugin and wrap it with Border so user can tell that the plugin is selected.

2020-11-04 12:06 UTC, shaulgo requested changes

2020-11-04 12:06 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +      const isSelected = blockProps.isFocused && !isOneBlockSelected;
When one block is selected, it's still selected? 
```suggestion
      const isSelected = blockProps.isFocused
```

2020-11-04 12:06 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
>        const isActive = isFocused && isEditorFocused;
do we need this?
My logic says that 
isSelected = when it's selected
isFocused = when _only it's selected_ && _editor is focused_, should be enough.

2020-11-04 17:36 UTC, maimonav commented on CHANGELOG.md
> +- `editor-common`
I did it to fix the spacing in the changelog, do you want me to change it straight from master?

2020-11-04 18:11 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +      const isSelected = blockProps.isFocused && !isOneBlockSelected;
I see 2 use cases here:
1. the block is part of selection (multiple blocks selected), this case is only to support border on every plugin.
2. the block is focused (only the block is selected).

2020-11-04 18:12 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
>        const isActive = isFocused && isEditorFocused;
Check out the change that I've made, isActive is just isFocused.

2020-11-04 18:14 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +      const isSelected = blockProps.isFocused && !isOneBlockSelected;
And no, if there is one block selected and the block is focused - than the block is focused.

2020-11-05 09:35 UTC, shaulgo approved these changes

2020-11-05 09:35 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +          [this.styles.hasFocus]: (isFocused && !noPluginBorder) || isSelected,
```suggestion
          [this.styles.hasFocus]: isFocused ? !noPluginBorder : isSelected,
```

2020-11-05 09:47 UTC, maimonav commented on packages/plugin-commons/web/src/consts.ts
> +export const pluginsWithoutInnerFocusWhenMultipleBlocksSelected = [ACCORDION];
done.

2020-11-05 09:47 UTC, maimonav commented on packages/plugin-commons/web/src/consts.ts
> +export const pluginsWithoutPointerEventsOnFocus = [ACCORDION];
done.

2020-11-05 09:47 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +          [this.styles.hideSelection]: !isActive,
done.

2020-11-05 09:47 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +      const shouldDisableInnerFocus =
done.

2020-11-05 10:47 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +          [theme.hasFocus]: isFocused,
```suggestion
          [theme.hasFocus]: isFocused ? !noPluginBorder : isSelected,
```

2020-11-05 11:00 UTC, shaulgo commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +        !isSelected && noPluginBorder && this.styles.noBorderOnHover,
!(isSelected && !isFocused && noPluginBorder) && this.styles.noBorder

2020-11-10 15:39 UTC, maimonav commented on packages/plugin-commons/web/src/Base/createBaseComponent.jsx
> +        !isSelected && noPluginBorder && this.styles.noBorderOnHover,
I changed it a bit, since this was not the solution.

2020-11-10 16:11 UTC, merged