Fix/undo-redo on android phones
wix-incubator/rich-content pull request #1763
Opened 2020-11-15 13:45 UTC by talevy17

2020-11-15 21:35 UTC, shaulgo requested changes

2020-11-15 21:35 UTC, shaulgo commented on CHANGELOG.md
> +- `editor`
?

2020-11-15 21:35 UTC, shaulgo commented on packages/plugin-undo-redo/web/src/createToolbar.tsx
> +            setEditorState(newEditorState);
```suggestion
         	const newState = utils.undo(getEditorState());
            setEditorState(newState);
```

2020-11-15 21:35 UTC, shaulgo commented on packages/plugin-undo-redo/web/src/createToolbar.tsx
> +            setEditorState(newEditorState);
let's do something more like this for undo/redo.

2020-11-15 21:35 UTC, shaulgo commented on packages/plugin-undo-redo/web/src/createToolbar.tsx
> +            setEditorState(newEditorState);
do you need to test for mobile? I think in korean you enter composition mode also in desktop.

2020-11-15 21:45 UTC, talevy17 commented on CHANGELOG.md
> +- `editor`
Fixed a mistake in changelog I noticed

2020-11-15 21:47 UTC, talevy17 commented on packages/plugin-undo-redo/web/src/createToolbar.tsx
> +            setEditorState(newEditorState);
I think checking the composition mode should be enough or at least do no harm, I’ll change

2020-11-16 09:11 UTC, shaulgo approved these changes

2020-11-16 09:11 UTC, shaulgo commented
add changelog and merge

2020-11-16 09:50 UTC, merged