[editor] fix: switching focus between inner-rce's in composition mode (Draft-js & Android bug)
wix-incubator/rich-content pull request #1784
Opened 2020-11-19 14:54 UTC by maimonav

In Mobile, using **Android** device & **Google** keyboard, when moving between Inner-rce's, the focus bumps to the previous editor that was focused, there are two `onFocus` actions that has been triggered because of Draft-js & Android event handlers bugs.
In order to fix it, when `onBlur` triggers (of the first Editor that is been blurred), setting the SelectionState to have `hasFocus` = false, disables the unwanted `onFocus` actions from triggering.
This change will only happen when blurring for Inner-RCE and EditorState is in CompositionMode.

2020-11-19 15:42 UTC, shaulgo requested changes

2020-11-19 15:42 UTC, shaulgo commented on packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
> +    });
```suggestion
    const selection = editorState.getSelection().merge({ hasFocus: false });
    const newEditorState = EditorState.set(editorState, { selection });
```

2020-11-22 08:06 UTC, maimonav commented on packages/editor/web/src/RichContentEditor/RichContentEditor.tsx
> +    });
Done.

2020-11-22 08:34 UTC, shaulgo approved these changes

2020-11-22 08:35 UTC, shaulgo approved these changes

2020-11-22 08:52 UTC, merged