[docs] improve: Theming API
wix-incubator/rich-content pull request #1788
Opened 2020-11-23 01:57 UTC by Barackos

2020-11-23 08:48 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
> -```
We are removing the support for this one, therefore the removal

2020-11-23 08:52 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
> -| wixTypography | WixTypography               | Ineffective atm (WIP). WixSiteObject of Fonts |
We remove `wixTypography` from docs as it is an internal wix-ricos object type

2020-11-23 14:06 UTC, mharsat requested changes
Add a simple API for the theme prop in the main ricos API page. Something like

```tsx
theme?: {
  parentClass?: string;
  palette?: PaletteColors | PalettePreset;
  customStyles?: RicosCustomTheme;
}
```

2020-11-23 14:06 UTC, mharsat commented on docs/docs/ricos/Theming.mdx
>  #### RicosCustomTheme
Both `RicosCustomTheme` and `CustomTextualStyle` tables are very repetitive and should be removed. Try to think of a different table-less representation.
For example, simply mention the props accepted in `RicosCustomTheme` without describing each and every one. Also `CSSProperties['fontSize']` is pure typescript code and not documentation, could also here mention the supported css properties without explaining their types (it's obvious in this case)

2020-11-23 14:06 UTC, mharsat commented on docs/docs/ricos/Theming.mdx
> +## parentClass (optional)
This is an explanation, not the API so no need to mention it's optional. Also, the titles are inconsistent, in this case you use the prop name `parentClass`, and in other cases you use a title name like Custom Styles. Choose one unified format

2020-11-23 19:18 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
>  ```
done

2020-11-23 19:23 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
> +You can also modify specific elements' colors (like text headers / links). See [Custom Styles](./Theming#custom-styles) API below.
To improve consistency I removed the "Fonts" title as it is not a prop of its own. Since customStyles is a different prop, it feels right to keep this redirection here, as one might want to figure out how to change headers colors, and turn first to the "Coloring" section.

2020-11-23 19:24 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
>  const customStyles: RicosCustomTheme = {
`RicosCustomStyles` is now the new guy in town

2020-11-24 10:03 UTC, mharsat requested changes

2020-11-24 10:03 UTC, mharsat commented on docs/docs/ricos/Theming.mdx
> +which you can now customize via the Custom Styles API below:
```suggestion
The `font-family` of textual content within Ricos is inherited from its wrapping component, while other typography properties like `font-size` are defined within Ricos.
Overriding these properties is done by setting the `customStyles`.
```

2020-11-25 08:58 UTC, Barackos commented on docs/docs/ricos/Theming.mdx
> +}
oops

2020-11-25 10:25 UTC, merged