[image] fix: blurry image on Safari when reloading the page
wix-incubator/rich-content pull request #1793
Opened 2020-11-24 09:18 UTC by maimonav

When reloading page with images in Safari, the `onLoad` event in `<img/>` is problematic, it fires only one time & due to inconsistency in Safari, sometimes it fires the `onLoad` without attaching the event to it, making the `onLoad` useless.

2020-11-24 14:29 UTC, shaulgo approved these changes

2020-11-24 16:00 UTC, maimonav commented on packages/plugin-image/web/src/image-viewer.jsx
> +    const imageClassName = this.styles.image;
:)

2020-11-24 16:02 UTC, maimonav commented on packages/plugin-image/web/src/image-viewer.jsx
> +        id={fadeIn ? 'highRes' : undefined}
Sure.

2020-11-25 08:12 UTC, shaulgo requested changes

2020-11-25 08:12 UTC, shaulgo commented on packages/plugin-image/web/src/image-viewer.jsx
> +    }
1. extract function
2. Add to explanation that image's onLoad isn't always called on safari when refreshing there for... (if someone needs to do any changes in the future, he will need to know)

2020-11-25 08:20 UTC, maimonav commented on packages/plugin-image/web/src/image-viewer.jsx
> +    }
done.

2020-11-25 12:21 UTC, merged