[ricos-content] schema migration from draft
wix-incubator/rich-content pull request #1794
Opened 2020-11-24 13:27 UTC by bchmn

2020-11-24 14:57 UTC, mharsat requested changes

2020-11-24 14:57 UTC, mharsat commented on packages/ricos-content/web/src/migrateSchema/consts.js
> +  codeeBlock: 'code-block',
typo

2020-11-24 14:57 UTC, mharsat commented on packages/ricos-content/web/src/migrateSchema/fromDraft.js
> +    nodes: parseTextBlock(block),
this should be an array of nodes, `parseTextBlock` returns a single node

2020-11-24 14:57 UTC, mharsat commented on packages/ricos-content/web/src/migrateSchema/fromDraft.js
> +    return textNodes;
If `currentRange === {}` (ranges is empty), are all these cases relevant?
For example, there will be no `offset` or `length`

2020-11-25 07:45 UTC, bchmn commented on packages/ricos-content/web/src/migrateSchema/fromDraft.js
> +    return textNodes;
that's correct but the else block needs to run, otherwise text blocks without ranges will be ignored. feel free to refactor however you see fit.

2020-11-25 11:21 UTC, mharsat approved these changes

2020-11-25 11:28 UTC, mharsat commented on packages/ricos-content/web/src/migrateSchema/fromDraft.js
> +    return textNodes;
I [added types](https://github.com/wix-incubator/rich-content/pull/1794/commits/09c5790d5adcb29c17bac81cbd238963f491b6e8) to for clarification and refactored accordingly, please review logic doesn't change

2020-11-25 12:20 UTC, bchmn commented on packages/ricos-content/web/src/migrateSchema/fromDraft.js
> +    return textNodes;
looks good

2020-11-25 12:27 UTC, merged