color picker ui fixes
wix-incubator/rich-content pull request #1806
Opened 2020-11-29 12:35 UTC by tamrat-bay

2020-12-13 16:48 UTC, shaulgo requested changes

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPicker.jsx
> +    this.setState({ color });
usually it's bad practice to have both the same value in both state and props. We strive for a single source of truth.

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPicker.jsx
> +        <CustomColorPicker {...this.props} onChange={this.onChangeConverted} />
let's have all of this component dynamically loaded. It should make it more simple and also the css will be dynamically loaded as well. 
So this file will not have dynamic imports. And you will do import(CustomColorPicker) dynamically where it's used.

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPicker.jsx
> +        <CustomColorPicker {...this.props} onChange={this.onChangeConverted} />
After you do that check how to prefetch a dynamic upload. So that it will start loading once the simple color panel is opened

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/src/Components/ColorPicker/CustomColorPicker.jsx
> +              className="hexColorInput"
let's use css modules

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/statics/styles/color-picker-react-colorful.scss
> +      z-index: 1;
is all the css here needed?

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/statics/styles/color-picker.scss
> +  width: auto;
why?

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/statics/styles/color-picker.scss
> +  left: 61%;
1. is it really suppose to be a percentage of something?
2. What does it mean percentage here?

2020-12-13 16:48 UTC, shaulgo commented on packages/plugin-commons/web/statics/styles/custom-color-picker-dialog.scss
> +  box-sizing: border-box;
We change box-sizing only for special needs. 
What's the need here? 
(Do you know what it does? or read about it)

2020-12-16 08:57 UTC, tamrat-bay commented on packages/plugin-commons/web/statics/styles/custom-color-picker-dialog.scss
> +  box-sizing: border-box;
I used it because I needed 12px spacing between the content and the border
without changing the width/height of the container

2020-12-16 09:50 UTC, shaulgo commented on packages/plugin-commons/web/statics/styles/custom-color-picker-dialog.scss
> +  box-sizing: border-box;
Everything should already be set to border-box. I don't think it's needed. If it's not border-box. We should check from where it's inheriting and why.

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-21 09:50 UTC, shaulgo approved these changes

2020-12-22 07:55 UTC, merged